# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "intern-project.fullname" . }}
  labels:
    {{- include "intern-project.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "intern-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "intern-project.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
              - containerPort: 4000
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          # Add additional environment variables as needed

        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
              - containerPort: 80
          # Add additional environment variables as needed

        - name: reverseproxy
          image: {{ .Values.reverseproxy.image.repository }}:{{ .Values.reverseproxy.image.tag }}
          ports:
              - containerPort: 8080
          # Add additional environment variables as needed

        - name: database
          image: {{ .Values.database.image.repository }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          # Add additional environment variables as needed

