apiVersion: v1
kind: Service
metadata:
  name: {{ include "intern-project.fullname" . }}
  labels:
    {{- include "intern-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    ports:
      - name: backend
        port: 4000
        targetPort: 4000
        protocol: TCP
      - name: frontend
        port: 80
        targetPort: 80
        protocol: TCP
      - name: reverseproxy
        port: 8080
        targetPort: 8080
        protocol: TCP
  selector:
    {{- include "intern-project.selectorLabels" . | nindent 4 }}
